name: MagazineStand
options:
  bundleIdPrefix: com.tokyonasu
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  MagazineStand:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: MagazineStand
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tokyonasu.MagazineStand
        PRODUCT_NAME: MagazineStand
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: マガジンスタンド
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: false
        INFOPLIST_KEY_NSUserTrackingUsageDescription: "広告の最適化のためにトラッキングの許可をお願いします"
        DEVELOPMENT_TEAM: 83VGKGSQUH
        CODE_SIGN_STYLE: Automatic
